{% set name = "seccomp-split" %}
{% set version = "2.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/seccomp/libseccomp/archive/v{{ version }}.tar.gz
  sha256: 36aa502c0461ae9efc6c93ec2430d6badd9bf91ecbe73806baf7b7c6f687ab4f

build:
  number: 1
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - automake
    - autoconf
    - libtool

test:
  commands:
    - test -l ${PREFIX}/libseccomp.so

outputs:
  - name: libseccomp
    script: install_lib.sh
    build:
      run_exports:
        # Has followed semver since 1.0.1 in 2012
        # https://abi-laboratory.pro/index.php?view=timeline&l=libseccomp
        - {{ pin_subpackage('libseccomp') }}
    requirements:
      build:
        - {{ compiler('c') }}
        - make  # [unix]
    test:
      commands:
        - test -f $PREFIX/lib/libseccomp.so
        - test -f $PREFIX/lib/libseccomp.a

  - name: seccomp
    script: install_python.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - sed
        - make  # [unix]
      host:
        - cython
        - python
        - pip
        - {{ pin_subpackage('libseccomp', exact=True) }}
      run:
        - python
        # The python package statitically links to libseccomp
        # so there is no need to add it here
    test:
      imports:
        - seccomp

about:
  home: https://github.com/seccomp/libseccomp
  license: LGPL-2.1-only
  license_file: LICENSE
  summary: 'libseccomp provides an easy to use, platform independent, interface to the Linux syscall filtering mechanism.'

  description: |
    The libseccomp library provides an easy to use, platform independent, 
    interface to the Linux Kernel's syscall filtering mechanism. The 
    libseccomp API is designed to abstract away the underlying BPF based 
    syscall filter language and present a more conventional function-call
    based filtering interface that should be familiar to, and easily 
    adopted by, application developers.
  dev_url: https://github.com/seccomp/libseccomp

extra:
  recipe-maintainers:
    - sodre
