travis:
  secure:
    BINSTAR_TOKEN: Scf45wYEo8lxQMjjZHYTjr8+jChRIbHO/zFjdCuYTZpFrrMjAlZpiVFeYizlPg03fofbkpaiQxLcnuO+lvaRZdBFvrZ4RlelMHls9elgOFIflfJstQaMNzT6M8ljVgjWVNZro5Fkseslu8RL3qxSQk+YEzLitriu6nvMkSK3n/rg0DikrT8uTQIDuFhOqgUiCLX4CvF+hD7e7bqnG4egNavugRafN8jyUMTS+A/9zs6TGKrm0DHuR04TafbwcndY5hK2deUggDfbasu8KY8TwA4TuVjfjR713WdDphPhMQJ4mZyFZrbWH7dih80BRrwOZH6mkcz5WvN9laMWIkjoNAQeFiiodigBHgGevxecDMB6KpG3wODuMD/enczx+ucdqn7J6CGx2YUJWpMN8E89K0lAlWR6DrDSmmNAhTK2sug+yajPG7k3xag80QN2MUTuAsYdiUVhNsV2J01B/rhAarxSNWEA2PTdYKXvaw4iBEPriSa9k42tTRN+N4wY0zjAw58Kh6pXB8qa+WQMhxxm5WeZqSfEdMA/BuW+7+NF/xJYV9XhQUlAw+TESiqlTiCFivRLqIXtTpHh/czDHtt/GHzE9+6b0RbierMYgxBW53OqoAkNr1WnP1zhgWT3vzN8bnc9MRq7KdiC5I4sJNmgjPmf2fdWPSK+Z+BPPw3jqUo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
